import { NodeType } from "@/types/workflow";

export const NODE_TYPE_CONFIG = {
  [NodeType.Shell]: {
    label: "Shell 命令",
    icon: "terminal",
    color: "#d97706",
    description: "执行终端命令",
  },
  [NodeType.Delay]: {
    label: "延时",
    icon: "timer",
    color: "#2563eb",
    description: "等待指定时间",
  },
  [NodeType.Notification]: {
    label: "通知",
    icon: "bell",
    color: "#7c3aed",
    description: "发送系统通知",
  },
  [NodeType.ClipboardRead]: {
    label: "读取剪贴板",
    icon: "clipboard-copy",
    color: "#0891b2",
    description: "读取剪贴板文本",
  },
  [NodeType.ClipboardWrite]: {
    label: "写入剪贴板",
    icon: "clipboard-paste",
    color: "#0e7490",
    description: "写入文本到剪贴板",
  },
  [NodeType.FileRead]: {
    label: "读取文件",
    icon: "file-input",
    color: "#65a30d",
    description: "读取文件内容",
  },
  [NodeType.FileWrite]: {
    label: "写入文件",
    icon: "file-output",
    color: "#4d7c0f",
    description: "写入内容到文件",
  },
  [NodeType.FileCopy]: {
    label: "复制文件",
    icon: "copy",
    color: "#16a34a",
    description: "复制文件到目标路径",
  },
  [NodeType.FileMove]: {
    label: "移动文件",
    icon: "file-symlink",
    color: "#15803d",
    description: "移动或重命名文件",
  },
  [NodeType.HttpRequest]: {
    label: "HTTP 请求",
    icon: "globe",
    color: "#dc2626",
    description: "发送 HTTP 请求",
  },
  [NodeType.Condition]: {
    label: "条件分支",
    icon: "git-branch",
    color: "#c026d3",
    description: "根据条件走不同分支",
  },
  [NodeType.Loop]: {
    label: "循环",
    icon: "repeat",
    color: "#ea580c",
    description: "遍历数组元素",
  },
  [NodeType.SubWorkflow]: {
    label: "子工作流",
    icon: "workflow",
    color: "#0d9488",
    description: "调用另一个工作流",
  },
  [NodeType.ScreenshotFull]: {
    label: "全屏截图",
    icon: "monitor",
    color: "#0284c7",
    description: "截取整个屏幕",
  },
  [NodeType.ScreenshotRegion]: {
    label: "区域截图",
    icon: "scan",
    color: "#0369a1",
    description: "截取指定区域",
  },
  [NodeType.AiChat]: {
    label: "AI 处理",
    icon: "sparkles",
    color: "#8b5cf6",
    description: "对话 / 总结 / 翻译 / OCR / 代码审查",
  },
  [NodeType.ImagePreview]: {
    label: "图片预览",
    icon: "image",
    color: "#06b6d4",
    description: "打开图片查看",
  },
  [NodeType.TextProcess]: {
    label: "文本处理",
    icon: "text-cursor-input",
    color: "#475569",
    description: "大小写/分割/替换/正则",
  },
  [NodeType.JsonProcess]: {
    label: "JSON/CSV",
    icon: "braces",
    color: "#0f766e",
    description: "解析/格式化/JSON↔CSV",
  },
  [NodeType.DataProcess]: {
    label: "数据统计",
    icon: "bar-chart-3",
    color: "#4338ca",
    description: "计数/求和/排序/过滤/去重",
  },
  [NodeType.RegexExtract]: {
    label: "正则提取",
    icon: "text-cursor-input",
    color: "#059669",
    description: "正则表达式匹配提取",
  },
  [NodeType.EmailSend]: {
    label: "发送邮件",
    icon: "mail",
    color: "#ea580c",
    description: "通过 SMTP 发送邮件",
  },
  [NodeType.Code]: {
    label: "代码执行",
    icon: "code",
    color: "#059669",
    description: "运行 JavaScript / Python 代码",
  },
  [NodeType.AppleScript]: {
    label: "AppleScript",
    icon: "apple",
    color: "#6366f1",
    description: "macOS 自动化脚本",
  },
  [NodeType.OpenApp]: {
    label: "启动应用",
    icon: "app-window",
    color: "#0ea5e9",
    description: "打开/聚焦/退出应用程序",
  },
  [NodeType.KeyboardType]: {
    label: "键盘输入",
    icon: "keyboard",
    color: "#f59e0b",
    description: "模拟键盘打字和快捷键",
  },
  [NodeType.UserInput]: {
    label: "用户输入",
    icon: "message-circle",
    color: "#ec4899",
    description: "弹窗获取用户输入",
  },
  [NodeType.FileWatch]: {
    label: "文件监听",
    icon: "folder-search",
    color: "#14b8a6",
    description: "监听文件/目录变化",
  },
  [NodeType.Comment]: { label: "注释", icon: "message-square", color: "#94a3b8", description: "添加备注说明" },
  [NodeType.VariableSet]: { label: "设置变量", icon: "variable", color: "#6d28d9", description: "设置全局/工作流变量" },
  [NodeType.VariableGet]: { label: "读取变量", icon: "variable", color: "#7c3aed", description: "读取变量值" },
  [NodeType.Database]: { label: "数据库", icon: "database", color: "#0d9488", description: "本地 SQLite 操作" },
  [NodeType.SqlQuery]: { label: "SQL 查询", icon: "table-2", color: "#0f766e", description: "自定义 SQL 语句" },
  [NodeType.Merge]: { label: "合并", icon: "merge", color: "#9333ea", description: "聚合多个上游输出" },
  [NodeType.BatchProcess]: { label: "批量处理", icon: "layers", color: "#ea580c", description: "并行处理数组元素" },
  [NodeType.ImageGenerate]: { label: "图片生成", icon: "image-plus", color: "#a855f7", description: "AI 文生图" },
  [NodeType.Tts]: { label: "语音合成", icon: "volume-2", color: "#8b5cf6", description: "文字转语音" },
  [NodeType.Stt]: { label: "语音识别", icon: "mic", color: "#7c3aed", description: "语音转文字" },
  [NodeType.IntentRecognition]: { label: "意图识别", icon: "brain", color: "#c026d3", description: "AI 语义分类路由" },
  [NodeType.KnowledgeWrite]: { label: "写入知识库", icon: "book-plus", color: "#059669", description: "存入向量知识库" },
  [NodeType.KnowledgeSearch]: { label: "知识检索", icon: "book-open", color: "#0d9488", description: "向量相似度搜索" },
  [NodeType.WebhookTrigger]: { label: "Webhook", icon: "webhook", color: "#dc2626", description: "HTTP 触发器" },
  [NodeType.ResultDialog]: { label: "结果展示", icon: "chat-bubble", color: "#3b82f6", description: "弹窗展示文本结果" },
  [NodeType.Agent]: { label: "AI Agent", icon: "brain", color: "#7c3aed", description: "多轮对话 AI 代理" },
  [NodeType.ListOperator]: { label: "列表操作", icon: "filter-list", color: "#0891b2", description: "过滤/排序/截取数组" },
  [NodeType.TemplateRender]: { label: "模板渲染", icon: "file-code", color: "#475569", description: "变量模板渲染引擎" },
  [NodeType.DocumentExtractor]: { label: "文档解析", icon: "file-search", color: "#16a34a", description: "解析 PDF/DOCX/HTML/TXT" },
  [NodeType.ParameterExtractor]: { label: "参数提取", icon: "text-cursor-input", color: "#8b5cf6", description: "LLM 结构化字段提取" },
  [NodeType.HumanReview]: { label: "人工审核", icon: "user-check", color: "#ec4899", description: "暂停等待人工确认" },
  [NodeType.Parallel]: { label: "并行分支", icon: "git-fork", color: "#0ea5e9", description: "多路径并行执行" },
} as const;

export const ADDABLE_NODE_TYPES = [
  NodeType.Shell,
  NodeType.Delay,
  NodeType.Notification,
  NodeType.ClipboardRead,
  NodeType.ClipboardWrite,
  NodeType.FileRead,
  NodeType.FileWrite,
  NodeType.FileCopy,
  NodeType.FileMove,
  NodeType.HttpRequest,
  NodeType.Condition,
  NodeType.Loop,
  NodeType.SubWorkflow,
  NodeType.ScreenshotFull,
  NodeType.ScreenshotRegion,
  NodeType.AiChat,
  NodeType.ImagePreview,
  NodeType.TextProcess,
  NodeType.JsonProcess,
  NodeType.DataProcess,
  NodeType.RegexExtract,
  NodeType.EmailSend,
  NodeType.Code,
  NodeType.AppleScript,
  NodeType.OpenApp,
  NodeType.KeyboardType,
  NodeType.UserInput,
  NodeType.FileWatch,
  NodeType.Comment,
  NodeType.VariableSet,
  NodeType.VariableGet,
  NodeType.Database,
  NodeType.SqlQuery,
  NodeType.Merge,
  NodeType.BatchProcess,
  NodeType.ImageGenerate,
  NodeType.Tts,
  NodeType.Stt,
  NodeType.IntentRecognition,
  NodeType.KnowledgeWrite,
  NodeType.KnowledgeSearch,
  NodeType.WebhookTrigger,
  NodeType.ResultDialog,
  NodeType.Agent,
  NodeType.ListOperator,
  NodeType.TemplateRender,
  NodeType.DocumentExtractor,
  NodeType.ParameterExtractor,
  NodeType.HumanReview,
  NodeType.Parallel,
] as const;
